name: CI

# Trigger on pushes to main and on pull‑request events
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the same Go image that Jenkins used
    container:
      image: golang:1.22
      # The container runs as root by default – no need for `-u root`

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Format check (go fmt) – same as the Jenkins “Format” stage
      - name: Format (go fmt)
        run: |
          go fmt ./...
          # Capture any files that were reformatted
          git diff --name-only > formatted-files.txt || true

      # 3️⃣ Upload the list of formatted files (if any)
      - uses: actions/upload-artifact@v4
        with:
          name: formatted-files
          path: formatted-files.txt

      # 4️⃣ Build the project – the composite action already builds
      #     and uploads the binary, so we just invoke it.
      - name: Go Build
        uses: ./.github/actions/go-build

      # 5️⃣ Run tests – the composite action runs `go test -v ./...`
      - name: Go Test
        uses: ./.github/actions/go-test