name: Go CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ (Optional) Install Go – the composite actions may already do this,
      #     but adding it here guarantees the correct version is available.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod   # automatically picks the version from go.mod
          cache: true

      # 3️⃣ Format step – same logic as the Jenkins stage
      - name: Format (go fmt)
        shell: bash
        run: |
          go fmt ./...
          git diff --name-only > formatted-files.txt || true

      # 4️⃣ Upload the list of formatted files (if any are there)
      - name: Upload formatted files
        uses: actions/upload-artifact@v4
        with:
          name: formatted-files
          path: formatted-files.txt

      # 5️⃣ Build – delegate to the reusable composite action
      - name: Build Go project
        uses: ./.github/actions/go-build

      # 6️⃣ Test – delegate to the reusable composite action
      - name: Run Go tests
        uses: ./.github/actions/go-test