# .github/workflows/build-format-test.yml
name: Build, Format and Test

# Trigger on pushes and PRs to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------------------------------------
      # 1️⃣  Checkout the repository
      # --------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------------------------
      # 2️⃣  Install Go (the composite actions don't do this for us)
      # --------------------------------------------------------------------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Pick the Go version that matches the go.mod file
          go-version-file: go.mod
          cache: true

      # --------------------------------------------------------------------
      # 3️⃣  Format the Go code (go fmt) – composite action
      # --------------------------------------------------------------------
      - name: Format Go code
        uses: ./.github/actions/go-fmt
        # The action automatically uploads `formatted-files.txt` as an artifact

      # --------------------------------------------------------------------
      # 4️⃣  Build the Go binary – composite action
      # --------------------------------------------------------------------
      - name: Build Go binary
        uses: ./.github/actions/go-build
        # The action automatically uploads the binary as `go-binary`

      # --------------------------------------------------------------------
      # 5️⃣  Run Go tests – composite action
      # --------------------------------------------------------------------
      - name: Run Go tests
        uses: ./.github/actions/go-test
        # The action just runs `go test -v ./...`

# --------------------------------------------------------------------
# Notes
# --------------------------------------------------------------------
# • The composite actions are expected to live in
#   .github/actions/go-fmt, .github/actions/go-build, and
#   .github/actions/go-test respectively.
# • All artifacts are uploaded by the composite actions themselves,
#   so we do not need any extra upload steps here.
# • Using the latest stable versions of the standard actions
#   (checkout@v4, setup-go@v5, upload-artifact@v4 inside the composites).