name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"   # adjust version as needed

      - name: Build
        run: go build -o build/app ./...

      - name: Run tests
        run: go test -v ./... | tee test-results.txt

      - name: Store binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: build/app

      - name: Store test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt