
name: Build, Format and Test 23

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    # Default permissions are sufficient for the actions used.
    # (actions: write, contents: read, etc.)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This step pulls the source code into the runner.

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Uses the Go version specified in go.mod
          go-version-file: go.mod
          cache: true
        # Installing Go is required before any Go‑specific composite action.

      - name: Format Go code
        uses: ./.github/actions/go-fmt
        # Runs `go fmt ./...` and uploads formatted‑files.txt.

      - name: Build Go binary
        uses: ./.github/actions/go-build
        # Builds the binary into `build/app` and uploads it as an artifact.

      - name: Run Go tests
        uses: ./.github/actions/go-test
        # Executes `go test -v ./...` and uploads the test results.
